# Generated by Django 4.2.11 on 2026-06-20 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_no', models.CharField(max_length=50, unique=True, verbose_name='配方编号')),
                ('name', models.CharField(max_length=200, verbose_name='配方名称')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='别名')),
                ('literature_page', models.CharField(blank=True, max_length=100, verbose_name='文献页码/章节')),
                ('era', models.CharField(blank=True, max_length=100, verbose_name='年代')),
                ('era_year', models.IntegerField(blank=True, null=True, verbose_name='具体年份')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='来源地区')),
                ('usage_category', models.CharField(choices=[('military', '军用'), ('fireworks', '烟花'), ('mining', '采矿'), ('signal', '信号'), ('medical', '医用'), ('other', '其他')], default='military', max_length=50, verbose_name='用途分类')),
                ('description', models.TextField(blank=True, verbose_name='配方描述')),
                ('safety_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='安全等级')),
                ('safety_note', models.TextField(blank=True, verbose_name='安全说明')),
                ('review_status', models.CharField(choices=[('draft', '草稿'), ('pending', '待评审'), ('recheck', '待复核'), ('approved', '评审通过'), ('rejected', '评审驳回')], default='draft', max_length=20, verbose_name='评审状态')),
                ('archive_status', models.CharField(choices=[('active', '在用'), ('archived', '已归档')], default='active', max_length=20, verbose_name='归档状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formulas', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '配方条目',
                'verbose_name_plural': '配方条目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='文献标题')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者/编纂者')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='出版/刊行年代')),
                ('dynasty', models.CharField(blank=True, max_length=100, verbose_name='朝代/时期')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='来源地区')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版机构/馆藏')),
                ('call_number', models.CharField(blank=True, max_length=100, verbose_name='索书号/编号')),
                ('source_type', models.CharField(choices=[('book', '典籍'), ('manuscript', '手抄本'), ('journal', '期刊论文'), ('archive', '档案'), ('other', '其他')], default='book', max_length=50, verbose_name='文献类型')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文献来源',
                'verbose_name_plural': '文献来源',
                'ordering': ['-publication_year'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_result', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('recheck', '待复核')], max_length=20, verbose_name='评审结果')),
                ('opinion', models.TextField(blank=True, verbose_name='评审意见')),
                ('risk_analysis', models.TextField(blank=True, verbose_name='风险分析')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评审时间')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='formulas.formula', verbose_name='所属配方')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
            ],
            options={
                'verbose_name': '安全评审',
                'verbose_name_plural': '安全评审',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='literature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='formulas.literature', verbose_name='文献出处'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成分名称')),
                ('chinese_name', models.CharField(blank=True, max_length=100, verbose_name='中文古称')),
                ('percentage', models.FloatField(default=0.0, verbose_name='占比 (%)')),
                ('remark', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='formulas.formula', verbose_name='所属配方')),
            ],
            options={
                'verbose_name': '配方成分',
                'verbose_name_plural': '配方成分',
                'ordering': ['formula', '-percentage'],
                'unique_together': {('formula', 'name')},
            },
        ),
    ]
