# Generated by Django 4.2.11 on 2026-06-20 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_formulas', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='formula',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='当前版本号'),
        ),
        migrations.AddField(
            model_name='literature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_literatures', to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '系统管理员'), ('curator', '文献馆员'), ('researcher', '研究员'), ('reviewer', '安全评审员'), ('auditor', '审计员'), ('guest', '访客')], default='guest', max_length=20, verbose_name='角色')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='所属部门/团队')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户角色档案',
                'verbose_name_plural': '用户角色档案',
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_risk_formula', '高风险配方'), ('missing_safety_note', '缺少安全说明'), ('review_overdue', '评审超期'), ('unapproved_access', '未授权访问尝试'), ('data_anomaly', '数据异常'), ('ingredient_conflict', '成分冲突'), ('other', '其他')], default='other', max_length=50, verbose_name='预警类型')),
                ('level', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=20, verbose_name='预警等级')),
                ('status', models.CharField(choices=[('open', '未处理'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='open', max_length=20, verbose_name='处理状态')),
                ('title', models.CharField(max_length=300, verbose_name='预警标题')),
                ('message', models.TextField(blank=True, verbose_name='预警详情')),
                ('risk_score', models.PositiveIntegerField(default=0, verbose_name='风险分值')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='formulas.formula', verbose_name='关联配方')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '风险预警',
                'verbose_name_plural': '风险预警',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('submit', '提交评审'), ('primary_review', '初审'), ('secondary_review', '复核'), ('final_approval', '终审'), ('rejection', '驳回'), ('revision', '修改待审')], max_length=30, verbose_name='流程节点')),
                ('from_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('pending', '待评审'), ('recheck', '待复核'), ('approved', '评审通过'), ('rejected', '评审驳回')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('draft', '草稿'), ('pending', '待评审'), ('recheck', '待复核'), ('approved', '评审通过'), ('rejected', '评审驳回')], max_length=20, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flows', to='formulas.formula', verbose_name='所属配方')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '评审流程记录',
                'verbose_name_plural': '评审流程记录',
                'ordering': ['formula', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='literature_attachments/%Y/%m/', verbose_name='附件文件')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='文件显示名称')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF文档'), ('image', '图片'), ('doc', 'Word文档'), ('other', '其他')], default='other', max_length=50, verbose_name='文件类型')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='文件说明')),
                ('page_reference', models.CharField(blank=True, max_length=100, verbose_name='对应页码/章节')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='formulas.literature', verbose_name='所属文献')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '文献附件',
                'verbose_name_plural': '文献附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('review', '评审'), ('submit', '提交'), ('archive', '归档'), ('unarchive', '解档'), ('download', '下载'), ('upload', '上传'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('view', '查看')], max_length=20, verbose_name='操作类型')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='对象ID')),
                ('target_name', models.CharField(blank=True, max_length=300, verbose_name='对象名称')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('old_value', models.TextField(blank=True, verbose_name='变更前数据')),
                ('new_value', models.TextField(blank=True, verbose_name='变更后数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='浏览器信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='formulas_op_user_id_ebab83_idx'), models.Index(fields=['operation_type', 'created_at'], name='formulas_op_operati_a699d1_idx'), models.Index(fields=['target_model', 'target_id'], name='formulas_op_target__1e5ca9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormulaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('name', models.CharField(max_length=200, verbose_name='配方名称')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='别名')),
                ('description', models.TextField(blank=True, verbose_name='配方描述')),
                ('safety_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='安全等级')),
                ('safety_note', models.TextField(blank=True, verbose_name='安全说明')),
                ('ingredients_json', models.TextField(verbose_name='成分数据(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='快照时间')),
                ('change_note', models.CharField(blank=True, max_length=500, verbose_name='版本变更说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='formulas.formula', verbose_name='所属配方')),
            ],
            options={
                'verbose_name': '配方版本',
                'verbose_name_plural': '配方版本',
                'ordering': ['formula', '-version'],
                'unique_together': {('formula', 'version')},
            },
        ),
    ]
