# Generated by Django 4.2.11 on 2026-06-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulas', '0002_formula_updated_by_formula_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('formula', '配方'), ('literature', '文献')], max_length=20, verbose_name='注释对象类型')),
                ('annotation_type', models.CharField(choices=[('term', '术语释义'), ('version_diff', '版本差异'), ('synonym', '成分名称异名'), ('authenticity', '出处真伪'), ('usage', '用途判断'), ('safety', '安全解读')], max_length=20, verbose_name='注释类型')),
                ('title', models.CharField(max_length=300, verbose_name='注释标题')),
                ('content', models.TextField(verbose_name='注释内容')),
                ('reference', models.TextField(blank=True, verbose_name='依据文献')),
                ('reference_page', models.CharField(blank=True, max_length=100, verbose_name='依据文献页码/章节')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotations', to=settings.AUTH_USER_MODEL, verbose_name='注释人')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='formulas.formula', verbose_name='关联配方')),
                ('literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='formulas.literature', verbose_name='关联文献')),
            ],
            options={
                'verbose_name': '学术注释',
                'verbose_name_plural': '学术注释',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('authenticity', '文献真伪争议'), ('ingredient', '成分辨识争议'), ('proportion', '比例换算争议'), ('dating', '年代断代争议'), ('usage', '用途判断争议'), ('safety', '安全解读争议'), ('other', '其他争议')], max_length=30, verbose_name='争议类型')),
                ('title', models.CharField(max_length=300, verbose_name='争议标题')),
                ('description', models.TextField(verbose_name='争议描述')),
                ('status', models.CharField(choices=[('open', '讨论中'), ('evidence', '证据收集中'), ('review', '专家评审中'), ('resolved', '已达成共识'), ('unresolved', '暂无定论'), ('withdrawn', '已撤回')], default='open', max_length=20, verbose_name='处理状态')),
                ('conclusion', models.TextField(blank=True, verbose_name='结论')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='formulas.formula', verbose_name='关联配方')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='formulas.literature', verbose_name='关联文献')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
            ],
            options={
                'verbose_name': '争议条目',
                'verbose_name_plural': '争议条目',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('open', '讨论中'), ('evidence', '证据收集中'), ('review', '专家评审中'), ('resolved', '已达成共识'), ('unresolved', '暂无定论'), ('withdrawn', '已撤回')], max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(choices=[('open', '讨论中'), ('evidence', '证据收集中'), ('review', '专家评审中'), ('resolved', '已达成共识'), ('unresolved', '暂无定论'), ('withdrawn', '已撤回')], max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='处理说明')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='formulas.dispute', verbose_name='所属争议')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '争议处理记录',
                'verbose_name_plural': '争议处理记录',
                'ordering': ['operated_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(choices=[('support', '支持'), ('oppose', '反对'), ('neutral', '中立')], max_length=20, verbose_name='立场')),
                ('viewpoint', models.TextField(verbose_name='观点内容')),
                ('evidence', models.TextField(blank=True, verbose_name='证据材料')),
                ('evidence_reference', models.CharField(blank=True, max_length=500, verbose_name='证据出处')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='formulas.dispute', verbose_name='所属争议')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '争议观点',
                'verbose_name_plural': '争议观点',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(verbose_name='修改前内容')),
                ('new_content', models.TextField(verbose_name='修改后内容')),
                ('edit_reason', models.CharField(blank=True, max_length=500, verbose_name='修改原因')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='formulas.academicannotation', verbose_name='所属注释')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '注释修改历史',
                'verbose_name_plural': '注释修改历史',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['dispute_type', 'status'], name='formulas_di_dispute_513299_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['formula', 'initiated_at'], name='formulas_di_formula_f6fe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['literature', 'initiated_at'], name='formulas_di_literat_7e12fc_idx'),
        ),
        migrations.AddIndex(
            model_name='academicannotation',
            index=models.Index(fields=['content_type', 'annotation_type'], name='formulas_ac_content_32718f_idx'),
        ),
        migrations.AddIndex(
            model_name='academicannotation',
            index=models.Index(fields=['formula', 'created_at'], name='formulas_ac_formula_5604b3_idx'),
        ),
        migrations.AddIndex(
            model_name='academicannotation',
            index=models.Index(fields=['literature', 'created_at'], name='formulas_ac_literat_4c84b5_idx'),
        ),
    ]
