# Generated by Django 4.2.11 on 2026-06-20 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulas', '0003_academicannotation_dispute_disputeprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=100, verbose_name='规范名称')),
                ('alias_name', models.CharField(db_index=True, max_length=100, verbose_name='异名/古称')),
                ('evidence', models.TextField(blank=True, verbose_name='依据证据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('source_literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_synonyms', to='formulas.literature', verbose_name='出处文献')),
            ],
            options={
                'verbose_name': '成分异名对照',
                'verbose_name_plural': '成分异名对照',
                'ordering': ['canonical_name'],
                'indexes': [models.Index(fields=['canonical_name', 'alias_name'], name='formulas_in_canonic_f5161d_idx')],
                'unique_together': {('canonical_name', 'alias_name')},
            },
        ),
    ]
