# Generated by Django 4.2.11 on 2026-06-20 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulas', '0004_ingredientsynonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='专题名称')),
                ('description', models.TextField(blank=True, verbose_name='专题描述')),
                ('category', models.CharField(choices=[('dynasty', '特定朝代'), ('region', '地区'), ('ingredient', '成分'), ('usage', '用途'), ('literature_system', '文献体系'), ('other', '其他')], default='other', max_length=30, verbose_name='主题类别')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('in_progress', '研究中'), ('completed', '已完成'), ('published', '已发布')], default='planning', max_length=20, verbose_name='研究状态')),
                ('research_note', models.TextField(blank=True, verbose_name='研究说明')),
                ('stage_conclusion', models.TextField(blank=True, verbose_name='阶段结论')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='研究开始日期')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='研究完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_topics', to=settings.AUTH_USER_MODEL, verbose_name='专题负责人')),
            ],
            options={
                'verbose_name': '研究专题',
                'verbose_name_plural': '研究专题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('formula', '配方'), ('literature', '文献'), ('annotation', '注释'), ('dispute', '争议'), ('review', '评审')], max_length=20, verbose_name='条目类型')),
                ('note', models.TextField(blank=True, verbose_name='归集说明')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_entries', to='formulas.academicannotation', verbose_name='关联注释')),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_entries', to='formulas.dispute', verbose_name='关联争议')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_entries', to='formulas.formula', verbose_name='关联配方')),
                ('literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_entries', to='formulas.literature', verbose_name='关联文献')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_entries', to='formulas.safetyreview', verbose_name='关联评审')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='formulas.researchtopic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '专题条目',
                'verbose_name_plural': '专题条目',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='关键词')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='formulas.researchtopic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '专题关键词',
                'verbose_name_plural': '专题关键词',
                'unique_together': {('topic', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='TopicNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('research_note', '研究说明'), ('conclusion', '阶段结论'), ('finding', '研究发现'), ('question', '待解问题')], default='research_note', max_length=20, verbose_name='笔记类型')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='formulas.researchtopic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '专题笔记',
                'verbose_name_plural': '专题笔记',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='参考资料标题')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='来源')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='formulas.researchtopic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '专题参考资料',
                'verbose_name_plural': '专题参考资料',
                'ordering': ['-added_at'],
            },
        ),
        migrations.DeleteModel(
            name='IngredientSynonym',
        ),
        migrations.AddIndex(
            model_name='topicentry',
            index=models.Index(fields=['topic', 'content_type'], name='formulas_to_topic_i_68bc01_idx'),
        ),
        migrations.AddIndex(
            model_name='researchtopic',
            index=models.Index(fields=['category', 'status'], name='formulas_re_categor_b4bb28_idx'),
        ),
        migrations.AddIndex(
            model_name='researchtopic',
            index=models.Index(fields=['leader', 'status'], name='formulas_re_leader__192f44_idx'),
        ),
    ]
